#!/bin/bash

##########################
#  Flush existing rules  #
##########################


iptables -F
iptables -t nat -F
iptables -t mangle -F
ip6tables -F


######################
#  Default policies  #
######################


# Drop all traffic
iptables -P INPUT DROP
iptables -P FORWARD DROP
iptables -P OUTPUT DROP
ip6tables -P INPUT DROP
ip6tables -P FORWARD DROP
ip6tables -P OUTPUT DROP

# Disable IPv6 completely
sysctl -w net.ipv6.conf.all.disable_ipv6=1
sysctl -w net.ipv6.conf.default.disable_ipv6=1
sysctl -w net.ipv6.conf.lo.disable_ipv6=1

# System Hardening
sysctl -w net.ipv4.icmp_echo_ignore_broadcasts=1
sysctl -w net.ipv4.conf.all.accept_source_route=0
sysctl -w net.ipv4.tcp_syncookies=1
sysctl -w net.ipv4.conf.all.accept_redirects=0
sysctl -w net.ipv4.conf.all.send_redirects=0
sysctl -w net.ipv4.conf.all.rp_filter=1
sysctl -w net.ipv4.conf.all.log_martians=1

# Block common scan types (Null, Xmas, FIN scans)
iptables -A INPUT -p tcp --tcp-flags ALL NONE -j DROP
iptables -A INPUT -p tcp --tcp-flags ALL ALL -j DROP
iptables -A INPUT -p tcp --tcp-flags ALL FIN -j DROP

# Drop malformed packets
iptables -A INPUT -m conntrack --ctstate INVALID -j DROP
iptables -A FORWARD -m conntrack --ctstate INVALID -j DROP

# Block fragmented packets (often used in evasion attacks)
iptables -A INPUT -f -j DROP

# Defend against SYN Flood attacks
iptables -A INPUT -p tcp --syn -m limit --limit 1/s --limit-burst 5 -j ACCEPT
iptables -A INPUT -p tcp --syn -j DROP

# Block incoming private/bogus IPs on public interface
iptables -A INPUT -s 10.0.0.0/8 -j DROP
iptables -A INPUT -s 169.254.0.0/16 -j DROP
iptables -A INPUT -s 172.16.0.0/12 -j DROP
iptables -A INPUT -s 192.168.0.0/16 -j DROP
iptables -A INPUT -s 224.0.0.0/4 -j DROP
iptables -A INPUT -s 240.0.0.0/5 -j DROP
iptables -A INPUT -s 127.0.0.0/8 ! -i lo -j DROP

# Drop Bogus Packets and Prevent IP Spoofing
iptables -A INPUT -p tcp --tcp-flags SYN,FIN SYN,FIN -j DROP
iptables -A INPUT -p tcp --tcp-flags SYN,RST SYN,RST -j DROP
iptables -A INPUT -p tcp --tcp-flags FIN,RST FIN,RST -j DROP
iptables -A INPUT -p tcp --tcp-flags FIN,ACK FIN -j DROP
iptables -A INPUT -p tcp --tcp-flags PSH,ACK PSH -j DROP
iptables -A INPUT -p tcp --tcp-flags ACK,URG URG -j DROP

# Block Tor and VPN Exit Nodes
iptables -A INPUT -m set --match-set tor-exit-nodes src -j DROP

# Allow established and related connections
iptables -A INPUT -m conntrack --ctstate ESTABLISHED,RELATED -j ACCEPT
iptables -A OUTPUT -m conntrack --ctstate ESTABLISHED,RELATED -j ACCEPT

# Allow loopback traffic
iptables -A INPUT -i lo -j ACCEPT
iptables -A OUTPUT -o lo -j ACCEPT

# Allow ICMP (ping)
iptables -A INPUT -p icmp -j ACCEPT
iptables -A OUTPUT -p icmp -j ACCEPT


###################
#  Allowed ports  #
###################


# Allow SSH with rate limiting to prevent brute-force attacks
iptables -A INPUT -p tcp --dport 22 -m conntrack --ctstate NEW -m recent --set
iptables -A INPUT -p tcp --dport 22 -m conntrack --ctstate NEW -m recent --update --seconds 60 --hitcount 4 -j DROP
iptables -A INPUT -p tcp --dport 22 -m conntrack --ctstate NEW -m recent --update --seconds 60 --hitcount 3 -j DROP
iptables -A INPUT -p tcp --dport 22 -m conntrack --ctstate NEW -m limit --limit 5/min --limit-burst 3 -j ACCEPT
iptables -A INPUT -p tcp --dport 22 -m conntrack --ctstate NEW -j DROP

# Allow DNS requests
iptables -A INPUT -p udp --dport 53 -j ACCEPT
iptables -A INPUT -p tcp --dport 53 -j ACCEPT
iptables -A OUTPUT -p udp --dport 53 -m owner --uid-owner systemd-resolve -j ACCEPT
iptables -A OUTPUT -p tcp --dport 53 -m owner --uid-owner systemd-resolve -j ACCEPT

# Allow HTTPS (browsing, Steam, Discord, MEGA Sync)
iptables -A INPUT -p tcp --dport 443 -j ACCEPT
iptables -A OUTPUT -p tcp --dport 443 -m owner --uid-owner user -j ACCEPT

# Allow Steam-specific ports
iptables -A INPUT -p udp --dport 27000:27100 -j ACCEPT
iptables -A INPUT -p tcp --dport 27015:27050 -j ACCEPT
iptables -A OUTPUT -p udp --dport 27000:27100 -j ACCEPT
iptables -A OUTPUT -p tcp --dport 27015:27050 -j ACCEPT

# Allow Discord voice servers
iptables -A INPUT -p udp --dport 50000:65535 -j ACCEPT
iptables -A OUTPUT -p udp --dport 50000:65535 -j ACCEPT

# Allow MEGA Sync
iptables -A INPUT -p tcp --dport 4443 -j ACCEPT
iptables -A OUTPUT -p tcp --dport 4443 -j ACCEPT

# Allow NTP for time sync
iptables -A INPUT -p udp --sport 123 -j ACCEPT
iptables -A OUTPUT -p udp --dport 123 -j ACCEPT  



#########
#  Log  #
#########


# Log and drop remaining packets
iptables -A INPUT -j LOG --log-prefix "[ALERT] BLOCKED: " --log-level 4


##########
#  Save  #
##########


# Save rules
iptables-save > /etc/iptables/iptables.rules
ip6tables-save > /etc/iptables/ip6tables.rules


##################
#  Print rules  ##
##################


# Show rules
iptables -nL

